spring:
  application:
    name: consumer-service

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: customer-group-v2
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.example.consumer.dto.Customer